---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - ../../reference-crs/required/gitops/

patches:
  - target:
      group: argoproj.io/v1alpha1
      version: v1alpha1
      kind: Application
      name: hub-config
    path: init-argocd-app.yaml


