---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-config
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: telco-hub/configuration/reference-crs/
    repoURL: https://github.com/jgato/telco-reference.git
    targetRevision: hub-automation
