---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-project.yaml
  - argocd-application.yaml
  - argocd-ssh-known-hosts-cm.yaml
  - ztp-repo.yaml

patches:
  # to patch the ArgoCD "hub-config" application
  # to contain the proper pointer to the
  # telco-hub RDS Manifests
  - target:
      group: argoproj.io/v1alpha1
      version: v1alpha1
      kind: Application
      name: hub-config
    path: overlays/init_installation_app.yaml
