---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: console-certificate
  namespace: cert-manager-operator
spec:
  commonName: selfsigned-ca.dns.name
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: console-ca-root-secret
