---
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.18
      type: ocp
      minVersion: 4.18.11
      maxVersion: 4.18.11
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
    targetCatalog: openshift-marketplace/redhat-operators-disconnected
    packages:
    - name: advanced-cluster-management
      channels:
      - name: release-2.13
    - name: multicluster-engine
      channels:
      - name: stable-2.8
    - name: topology-aware-lifecycle-manager
      channels:
      - name: stable
    - name: local-storage-operator
      channels:
      - name: stable
    - name: odf-operator
      channels:
      - name: stable-4.18
    - name: odf-dependencies
      channels:
      - name: stable-4.18
    - name: odf-csi-addons-operator
      channels:
      - name: stable-4.18
    - name: ocs-client-operator
      channels:
      - name: stable-4.18
    - name: cephcsi-operator
      channels:
      - name: stable-4.18
    - name: odf-prometheus-operator
      channels:
      - name: stable-4.18
    - name: odf-multicluster-orchestrator
      channels:
      - name: stable-4.18
    - name: ocs-operator
      channels:
      - name: stable-4.18
    - name: rook-ceph-operator
      channels:
      - name: stable-4.18
    - name: mcg-operator
      channels:
      - name: stable-4.18
    - name: odr-hub-operator
      channels:
      - name: stable-4.18
    - name: odr-cluster-operator
      channels:
      - name: stable-4.18
    - name: recipe
      channels:
      - name: stable-4.18
    - name: openshift-gitops-operator
      channels:
      - name: gitops-1.15
    - name: redhat-oadp-operator
      channels:
      - name: stable-1.4
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  - name: registry.redhat.io/openshift4/ztp-site-generate-rhel8:v4.18.0
  - name: registry.redhat.io/rhel8/support-tools:8.9-7
