---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    installer.open-cluster-management.io/mce-subscription-spec: '{"source": "redhat-operators-disconnected", "installPlanApproval": "Automatic"}'
    installer.open-cluster-management.io/oadp-subscription-spec: '{"source": "redhat-operators-disconnected", "installPlanApproval": "Automatic"}'
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  availabilityConfig: High
  enableClusterBackup: false
  ingress: {}
  overrides:
    components:
    - enabled: true
      name: app-lifecycle
    - enabled: true
      name: cluster-lifecycle
    - enabled: true
      name: cluster-permission
    - enabled: true
      name: console
    - enabled: true
      name: grc
    - enabled: true
      name: insights
    - enabled: true
      name: multicluster-engine
    - enabled: true
      name: multicluster-observability
    - enabled: true
      name: search
    - enabled: true
      name: submariner-addon
    - enabled: true
      name: volsync
    - enabled: true
      name: cluster-backup
    - enabled: true
      name: siteconfig
  separateCertificateManagement: false
