# kustomization file including different overays over the
# reference crs
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # comment the optional components when not using them
  - reference-crs/optional/lso/
  - reference-crs/optional/odf-internal/
  # everything under required is mandatory
  - reference-crs/required/gitops/
  - reference-crs/required/acm/
  - reference-crs/required/talm/
  # but, include this content if you want to include the argocd
  # configuration and apps for gitops ztp management of cluster
  # installation and configuration
  # - reference-crs/required/gitops/ztp-installation

# following the different overlays to patch
# the different configurations. In case you are not using some of the
# optional components, comment the proper patches
#
patches:
  # if you use LocalStorage operator, edit and configure the patch
  - target:
      group: local.storage.openshift.io
      version: v1
      kind: LocalVolume
      name: local-disks
    path: example-overlays-config/lso/local-storage-disks-patch.yaml

  # configure storage for MCO, it can difer depending on your configured
  # storage
  - target:
      group: observability.open-cluster-management.io
      version: v1beta2
      kind: MultiClusterObservability
      name: observability
    path: example-overlays-config/acm/storage-mco-patch.yaml
