# patching mco StorageClass

- op: replace
  path: /spec/databaseStorage/storageClassName
  value: "ocs-storagecluster-cephfs" #filesystem StorageClass

- op: replace
  path: /spec/filesystemStorage/storageClassName
  value: "ocs-storagecluster-cephfs" #filesystem StorageClass

- op: replace
  path: /spec/imageStorage/storageClassName
  value: "ocs-storagecluster-cephfs" #filesystem StorageClass

# connected environmet

- op: remove
  path: /spec/mirrorRegistryRef

- op: replace
  path: "/spec/osImages"
  value:
    - cpuArchitecture: "x86_64"
      openshiftVersion: "4.17"
      rootFSUrl:  https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos-4.17.0-x86_64-live-rootfs.x86_64.img
      url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies//rhcos-4.17.0-x86_64-live.x86_64.iso
      version: "417.94.202409121747-0"
