---
# It is not expected that this kustomization will be used directly. Most deployments will create an overlay with custom values for environment specific values (eg URL for gitops, disks for LSO, etc). The overlay will include the resources listed here as bases.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - optional/lso/
  - optional/odf-internal/
  - required/gitops/
  - required/acm/
  - required/talm/
  # Include this content if you want to include the argocd
  # configuration and apps for gitops ztp management of cluster
  # installation and configuration
  - required/gitops/ztp-installation

patches:
  - target:
      group: observability.open-cluster-management.io
      version: v1beta2
      kind: MultiClusterObservability
      name: observability
    path: overlays/storage-mco-patch.yaml
  - target:
      group: agent-install.openshift.io
      version: v1beta1
      kind: AgentServiceConfig
      name: agent
    path: overlays/options-agentserviceconfig-patch.yaml
  - target:
      group: local.storage.openshift.io
      version: v1
      kind: LocalVolume
      name: local-disks
    path: overlays/loca-storage-disks-patch.yaml
