---
# It is not expected that this kustomization will be used directly. Most deployments will create an overlay with custom values for environment specific values (eg URL for gitops, disks for LSO, etc). The overlay will include the resources listed here as bases.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - optional/lso/
  - optional/odf-internal/
  - required/gitops/
  - required/acm/
  - required/talm/
  # Include this content if you want to include the argocd
  # configuration and apps for gitops ztp management of cluster
  # installation and configuration
  # - required/gitops/ztp-installation
